language: ruby
sudo: true
rvm:
  - 2.0.0
jdk:
  - oraclejdk8
before_script:
  - chmod 0755 ci/travis.rb
script:
  - ci/travis.rb
before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk