language: ruby
sudo: true
dist: trusty
rvm:
  - 2.3
python:
  - "3.1"
node_js:
  - 7
before_script:
  - chmod 0755 ci/travis.rb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start -screen 0 1280x1024x16
script:
  - ci/travis.rb
addons:
  firefox: "44.0.2"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - mysql
after_failure:
  - cat target/surefire-reports/*.txt
  - cat install/glassfish4/glassfish/domains/domain1/logs/*.log
  - cat yo/npm-debug.log
