language: ruby
sudo: true
dist: trusty
rvm:
  - 2.0.0
python:
  - "3.1"
node_js:
  - "6"
before_script:
  - chmod 0755 ci/travis.rb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - ci/travis.rb
addons:
  - firefox: "44.0.2"
services:
  - mysql
after_failure:
  - cat target/surefire-reports/*.txt
  - cat /opt/glassfish4/glassfish/domains/domain1/logs/*.log
  - cat yo/npm-debug.log 